model_name: "openai/gpt-oss-120b"
input_file: "test/test.pdf"
model_type: "OpenAIModel"
api_key: "nvapi"
file_format: "md"
source_language: "English"
target_language: "Japanese"
base_url: "https://integrate.api.nvidia.com/v1"














